---
- name: web config
  hosts: webservers
  become: true
  tasks:
    - name: docker.io installation
      apt:
        name: docker.io
        update_cache: yes
        state: present

    - name: pip3 installation
      apt:
        name: python3-pip
        state: present

    - name: docker module installation
      pip:
        name: docker
        state: present

    - name: docker DVWA container download
      docker_container:
        name: dvwaa
        image: cyberxsecurity/dvwa
        restart: always
        state: started
        published_ports: 80:80

    - name: docker service enable
      systemd:
        name: docker
        enabled: yes